project:
  type: website
  output-dir: _site

website:
  title: "Credit Default Analysis"
  navbar:
    left:
      - href: ./for_pages/index.qmd
        text: Home
      - href: ./for_pages/about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
